### PR TITLE
Can custom the locale of the calendar

### PR DESCRIPTION
**Pull request by cprodhomme**
Need to use the option `locale` for `fullcalendar, '>= 3.4'`

https://fullcalendar.io/docs/locale

### CODE REVIEW

**Comment by djalmaaraujo** [comment]
This is documentation, right? It doesnt work. How you are passing?
```
index_as_calendar ({
    :ajax => false,
    :includes => [:client, :product],
    :locale => 'pt',
    :fullCalendarOptions => {
      :locale => 'pt'
    }
```

like this? which one is correct?

**Comment by cprodhomme** [comment]
I don't know anymore :/

**Comment by djalmaaraujo** [comment]
LoL

That's ok. Thanks

Em sex, 14 de jun de 2019 13:00, cprodhomme <notifications@github.com>
escreveu:

**Comment by tracyloisel** [comment]
I do it successfully this way

```
  index_as_calendar(ajax: true,
                    includes: %i(lead telepro shop),
                    start_date: :meeting_at,
                    fullCalendarOptions: {locale: I18n.locale},
                    )
```

**Pull request closed without merging**
